### ISSUE TITLE
虎9高德地图新版本适配车机的包

### ISSUE THREAD

**Issue by Gerrylinux** [zuo-qirun/Chery-Tiggo9-Install-software#2]
请问有没有高德地图和车机适配的apk包，现在找了一个包，启用后显示有些别扭。不是全屏展示，底图没有铺平

**Comment by Gerrylinux** [comment]
![a1e2c33d136420ea6907cb09647b4e6](https://github.com/user-attachments/assets/8bb2c1fb-1c3c-4624-a37b-63da6a38aa76)

**Comment by zuo-qirun** [comment]
您好 没有收集到适配的安装包😓我们这也用的是带黑边的安装包😟

**Comment by Gerrylinux** [comment]
作者你好，分享些车机的软件，可以集成到你tiggo9.zuoqirun.top站点
https://share.feijipan.com/s/XWCYComI
